// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzwnbkayxdnutozjiecl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56d25ia2F5eGRudXRvemppZWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzkwNDIsImV4cCI6MjA2NzMxNTA0Mn0.fdUZwN5Bjk4oK4FPUe1jC1fle0JmWWoZEYvA7hK2Y0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});